import NSFormal.FlowAveraging
import NSFormal.Domain

/-!
# Strongly continuous Koopman averages

The operator-valued Bochner average in `FlowAveraging.lean` is appropriate for
operator-norm-continuous families.  Koopman groups generated by continuous flows
are generally only *strongly* continuous.  This file constructs their normalized
averages by integrating each orbit in the Hilbert space and then proving that the
result is a bounded linear operator.  No operator-norm continuity is assumed.
-/

open MeasureTheory
open scoped Interval Topology ENNReal

noncomputable section

/-! ## Continuous maps carried by a flow -/

/-- A time slice of a continuous flow, regarded as a continuous self-map. -/
def flowContinuousMap {α : Type*} [TopologicalSpace α]
    (flow : Flow ℝ α) (s : ℝ) : C(α, α) :=
  ⟨flow s, flow.continuous_toFun s⟩

/-- Joint continuity of a flow gives continuity of its time slices in the
compact-open topology. -/
theorem flowContinuousMap_continuous
    {α : Type*} [TopologicalSpace α] (flow : Flow ℝ α) :
    Continuous (flowContinuousMap flow) := by
  apply ContinuousMap.continuous_of_continuous_uncurry
  exact flow.cont'

/-! ## Strongly continuous measure-preserving Koopman groups -/

/-- The scalar `L²` Koopman operator associated with a time slice of a
measure-preserving flow. -/
def measurePreservingFlowKoopman
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    (μ : Measure α) (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (s : ℝ) : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ :=
  measurePreservingKoopman μ (flow s) (hmeasure s)

/-- Each time slice of the Koopman family is a contraction. -/
theorem measurePreservingFlowKoopman_norm_le_one
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    (μ : Measure α) (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ) (s : ℝ) :
    ‖measurePreservingFlowKoopman μ flow hmeasure s‖ ≤ 1 := by
  exact measurePreservingKoopman_norm_le_one μ (flow s) (hmeasure s)

/-- A continuous measure-preserving flow induces a strongly continuous Koopman
orbit on scalar `L²`.  This is strong continuity at every seed, not the false
claim that the family is continuous in operator norm. -/
theorem measurePreservingFlowKoopman_stronglyContinuous
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (seed : Lp ℝ 2 μ) :
    Continuous (fun s => measurePreservingFlowKoopman μ flow hmeasure s seed) := by
  change Continuous (fun s =>
    Lp.compMeasurePreserving (flowContinuousMap flow s) (hmeasure s) seed)
  exact continuous_const.compMeasurePreservingLp
    (flowContinuousMap_continuous flow) hmeasure (by norm_num)

/-- Koopman transport respects the additive flow law.  The order here matches
pullback: first transport by `s`, then by `τ`, giving time `s + τ`. -/
theorem measurePreservingFlowKoopman_compose
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    (μ : Measure α) (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (τ s : ℝ) (seed : Lp ℝ 2 μ) :
    measurePreservingFlowKoopman μ flow hmeasure τ
        (measurePreservingFlowKoopman μ flow hmeasure s seed) =
      measurePreservingFlowKoopman μ flow hmeasure (s + τ) seed := by
  change Lp.compMeasurePreserving (flow τ) (hmeasure τ)
      (Lp.compMeasurePreserving (flow s) (hmeasure s) seed) =
    Lp.compMeasurePreserving (flow (s + τ)) (hmeasure (s + τ)) seed
  rw [← Lp.compMeasurePreserving_comp_apply seed (hmeasure s) (hmeasure τ)]
  have hmaps : (flow s ∘ flow τ) = flow (s + τ) := by
    funext x
    exact (flow.map_add s τ x).symm
  apply Subtype.ext
  exact AEEqFun.compMeasurePreserving_congr seed.1
    ((hmeasure s).comp (hmeasure τ)) (hmeasure (s + τ)).measurable
    (Filter.Eventually.of_forall (congrFun hmaps))

/-- Time zero acts as the identity Koopman operator. -/
theorem measurePreservingFlowKoopman_zero_apply
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    (μ : Measure α) (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (seed : Lp ℝ 2 μ) :
    measurePreservingFlowKoopman μ flow hmeasure 0 seed = seed := by
  change Lp.compMeasurePreserving (flow 0) (hmeasure 0) seed = seed
  apply Subtype.ext
  calc
    seed.1.compMeasurePreserving (flow 0) (hmeasure 0) =
        seed.1.compMeasurePreserving id (MeasurePreserving.id μ) := by
      exact AEEqFun.compMeasurePreserving_congr seed.1 (hmeasure 0)
        measurable_id
        (Filter.Eventually.of_forall (congrFun flow.map_zero))
    _ = seed.1 := AEEqFun.compMeasurePreserving_id seed.1

/-- Pullback by a measure-preserving flow is unitary: its Hilbert adjoint is
pullback by the inverse-time map. -/
theorem measurePreservingFlowKoopman_adjoint
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    (μ : Measure α) (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ) (τ : ℝ) :
    (measurePreservingFlowKoopman μ flow hmeasure τ).adjoint =
      measurePreservingFlowKoopman μ flow hmeasure (-τ) := by
  apply ContinuousLinearMap.ext
  intro x
  apply ext_inner_left ℝ
  intro y
  rw [ContinuousLinearMap.adjoint_inner_right]
  have hback :
      measurePreservingFlowKoopman μ flow hmeasure τ
          (measurePreservingFlowKoopman μ flow hmeasure (-τ) x) = x := by
    rw [measurePreservingFlowKoopman_compose]
    simpa using measurePreservingFlowKoopman_zero_apply μ flow hmeasure x
  have hisometry :=
    (Lp.compMeasurePreservingₗᵢ ℝ (flow τ) (hmeasure τ)).inner_map_map
      y (measurePreservingFlowKoopman μ flow hmeasure (-τ) x)
  change inner ℝ
      (measurePreservingFlowKoopman μ flow hmeasure τ y)
      (measurePreservingFlowKoopman μ flow hmeasure τ
        (measurePreservingFlowKoopman μ flow hmeasure (-τ) x)) =
      inner ℝ y (measurePreservingFlowKoopman μ flow hmeasure (-τ) x)
    at hisometry
  simpa only [hback] using hisometry

/-! ## Pointwise Bochner averages of strongly continuous contractions -/

/-- The underlying linear map obtained by integrating each strongly continuous
operator orbit.  Linearity follows from pointwise linearity and Bochner
integration; no topology on the operator family is used. -/
def strongOperatorIntervalAverageLinear
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (operators : ℝ → E →L[ℝ] E) (L : ℝ)
    (hcontinuous : ∀ seed, Continuous (fun s => operators s seed)) :
    E →ₗ[ℝ] E where
  toFun seed := L⁻¹ • ∫ s in (0 : ℝ)..L, operators s seed
  map_add' x y := by
    rw [← smul_add]
    congr 1
    simpa only [map_add] using intervalIntegral.integral_add
      ((hcontinuous x).intervalIntegrable 0 L)
      ((hcontinuous y).intervalIntegrable 0 L)
  map_smul' c x := by
    simp only [map_smul, intervalIntegral.integral_smul, smul_smul,
      RingHom.id_apply]
    rw [mul_comm]

/-- A positive normalized interval average of strongly continuous contractions
does not increase the norm of any vector. -/
theorem strongOperatorIntervalAverageLinear_norm_le
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (operators : ℝ → E →L[ℝ] E) (L : ℝ) (hL : 0 < L)
    (hcontinuous : ∀ seed, Continuous (fun s => operators s seed))
    (hcontract : ∀ s, ‖operators s‖ ≤ 1) (seed : E) :
    ‖strongOperatorIntervalAverageLinear operators L hcontinuous seed‖ ≤ ‖seed‖ := by
  have hintegral :
      ‖∫ s in (0 : ℝ)..L, operators s seed‖ ≤ ‖seed‖ * L := by
    have hbound := intervalIntegral.norm_integral_le_of_norm_le_const
      (a := (0 : ℝ)) (b := L) (C := ‖seed‖)
      (f := fun s => operators s seed) (fun s _hs => by
        simpa using (operators s).le_of_opNorm_le (hcontract s) seed)
    simpa [abs_of_pos hL] using hbound
  rw [strongOperatorIntervalAverageLinear, LinearMap.coe_mk,
    AddHom.coe_mk, norm_smul, Real.norm_eq_abs, abs_inv, abs_of_pos hL]
  calc
    L⁻¹ * ‖∫ s in (0 : ℝ)..L, operators s seed‖ ≤
        L⁻¹ * (‖seed‖ * L) :=
      mul_le_mul_of_nonneg_left hintegral (inv_nonneg.mpr hL.le)
    _ = ‖seed‖ := by field_simp

/-- The normalized pointwise Bochner average as a genuine bounded linear
operator.  The construction requires only strong continuity and a uniform
contraction bound. -/
def strongOperatorIntervalAverage
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (operators : ℝ → E →L[ℝ] E) (L : ℝ) (hL : 0 < L)
    (hcontinuous : ∀ seed, Continuous (fun s => operators s seed))
    (hcontract : ∀ s, ‖operators s‖ ≤ 1) : E →L[ℝ] E :=
  (strongOperatorIntervalAverageLinear operators L hcontinuous).mkContinuous 1
    (fun seed => by
      simpa using strongOperatorIntervalAverageLinear_norm_le
        operators L hL hcontinuous hcontract seed)

@[simp]
theorem strongOperatorIntervalAverage_apply
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (operators : ℝ → E →L[ℝ] E) (L : ℝ) (hL : 0 < L)
    (hcontinuous : ∀ seed, Continuous (fun s => operators s seed))
    (hcontract : ∀ s, ‖operators s‖ ≤ 1) (seed : E) :
    strongOperatorIntervalAverage operators L hL hcontinuous hcontract seed =
      L⁻¹ • ∫ s in (0 : ℝ)..L, operators s seed := by
  rfl

/-- The strongly constructed average has operator norm at most one. -/
theorem strongOperatorIntervalAverage_norm_le_one
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (operators : ℝ → E →L[ℝ] E) (L : ℝ) (hL : 0 < L)
    (hcontinuous : ∀ seed, Continuous (fun s => operators s seed))
    (hcontract : ∀ s, ‖operators s‖ ≤ 1) :
    ‖strongOperatorIntervalAverage operators L hL hcontinuous hcontract‖ ≤ 1 := by
  apply LinearMap.mkContinuous_norm_le
  norm_num

/-- For a strongly continuous contraction representation, translating the
average by time `τ` changes it only through the two endpoint intervals. -/
theorem strongOperatorIntervalAverage_translate_sub_eq_endpoints
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (operators : ℝ → E →L[ℝ] E) (L : ℝ) (hL : 0 < L)
    (hcontinuous : ∀ seed, Continuous (fun s => operators s seed))
    (hcontract : ∀ s, ‖operators s‖ ≤ 1)
    (hcompose : ∀ τ s seed,
      operators τ (operators s seed) = operators (s + τ) seed)
    (τ : ℝ) (seed : E) :
    operators τ
        (strongOperatorIntervalAverage operators L hL hcontinuous hcontract seed) -
      strongOperatorIntervalAverage operators L hL hcontinuous hcontract seed =
      L⁻¹ • ((∫ s in L..L + τ, operators s seed) -
        ∫ s in (0 : ℝ)..τ, operators s seed) := by
  have hint : ∀ a b : ℝ,
      IntervalIntegrable (fun s => operators s seed) volume a b :=
    fun a b => (hcontinuous seed).intervalIntegrable a b
  have hendpoint :
      (∫ s in τ..L + τ, operators s seed) -
          ∫ s in (0 : ℝ)..L, operators s seed =
        (∫ s in L..L + τ, operators s seed) -
          ∫ s in (0 : ℝ)..τ, operators s seed := by
    rw [← intervalIntegral.integral_add_adjacent_intervals
      (hint τ 0) (hint 0 (L + τ))]
    rw [← intervalIntegral.integral_add_adjacent_intervals
      (hint 0 L) (hint L (L + τ))]
    rw [intervalIntegral.integral_symm]
    abel
  rw [strongOperatorIntervalAverage_apply, map_smul]
  rw [← (operators τ).intervalIntegral_comp_comm (hint 0 L)]
  simp_rw [hcompose]
  rw [intervalIntegral.integral_comp_add_right
    (fun s => operators s seed) τ]
  simp only [zero_add]
  rw [← smul_sub, hendpoint]

/-- The endpoint identity gives an explicit strong-operator transport defect:
the normalized average is `2 |τ| / L`-approximately invariant in `L²` (or in
any Banach space carrying the contraction representation). -/
theorem strongOperatorIntervalAverage_translate_sub_norm_le
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (operators : ℝ → E →L[ℝ] E) (L : ℝ) (hL : 0 < L)
    (hcontinuous : ∀ seed, Continuous (fun s => operators s seed))
    (hcontract : ∀ s, ‖operators s‖ ≤ 1)
    (hcompose : ∀ τ s seed,
      operators τ (operators s seed) = operators (s + τ) seed)
    (τ : ℝ) (seed : E) :
    ‖operators τ
        (strongOperatorIntervalAverage operators L hL hcontinuous hcontract seed) -
      strongOperatorIntervalAverage operators L hL hcontinuous hcontract seed‖ ≤
      (2 * |τ| / L) * ‖seed‖ := by
  rw [strongOperatorIntervalAverage_translate_sub_eq_endpoints
    operators L hL hcontinuous hcontract hcompose τ seed]
  have hpoint : ∀ s : ℝ, ‖operators s seed‖ ≤ ‖seed‖ := by
    intro s
    simpa using (operators s).le_of_opNorm_le (hcontract s) seed
  have hright :
      ‖∫ s in L..L + τ, operators s seed‖ ≤ ‖seed‖ * |τ| := by
    have hbound := intervalIntegral.norm_integral_le_of_norm_le_const
      (a := L) (b := L + τ) (C := ‖seed‖)
      (f := fun s => operators s seed) (fun s _hs => hpoint s)
    simpa only [add_sub_cancel_left] using hbound
  have hleft :
      ‖∫ s in (0 : ℝ)..τ, operators s seed‖ ≤ ‖seed‖ * |τ| := by
    have hbound := intervalIntegral.norm_integral_le_of_norm_le_const
      (a := (0 : ℝ)) (b := τ) (C := ‖seed‖)
      (f := fun s => operators s seed) (fun s _hs => hpoint s)
    simpa using hbound
  rw [norm_smul, Real.norm_eq_abs, abs_inv, abs_of_pos hL]
  have hdiff :
      ‖(∫ s in L..L + τ, operators s seed) -
          ∫ s in (0 : ℝ)..τ, operators s seed‖ ≤
        2 * (‖seed‖ * |τ|) := by
    calc
      ‖(∫ s in L..L + τ, operators s seed) -
          ∫ s in (0 : ℝ)..τ, operators s seed‖ ≤
          ‖∫ s in L..L + τ, operators s seed‖ +
            ‖∫ s in (0 : ℝ)..τ, operators s seed‖ := norm_sub_le _ _
      _ ≤ ‖seed‖ * |τ| + ‖seed‖ * |τ| := add_le_add hright hleft
      _ = 2 * (‖seed‖ * |τ|) := by ring
  calc
    L⁻¹ * ‖(∫ s in L..L + τ, operators s seed) -
        ∫ s in (0 : ℝ)..τ, operators s seed‖ ≤
        L⁻¹ * (2 * (‖seed‖ * |τ|)) :=
      mul_le_mul_of_nonneg_left hdiff (inv_nonneg.mpr hL.le)
    _ = (2 * |τ| / L) * ‖seed‖ := by field_simp

/-- An additive one-parameter representation commutes with its own normalized
strong interval average. -/
theorem strongOperatorIntervalAverage_commute
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (operators : ℝ → E →L[ℝ] E) (L : ℝ) (hL : 0 < L)
    (hcontinuous : ∀ seed, Continuous (fun s => operators s seed))
    (hcontract : ∀ s, ‖operators s‖ ≤ 1)
    (hcompose : ∀ τ s seed,
      operators τ (operators s seed) = operators (s + τ) seed)
    (τ : ℝ) :
    operators τ ∘L
        strongOperatorIntervalAverage operators L hL hcontinuous hcontract =
      strongOperatorIntervalAverage operators L hL hcontinuous hcontract ∘L
        operators τ := by
  apply ContinuousLinearMap.ext
  intro seed
  simp only [ContinuousLinearMap.comp_apply,
    strongOperatorIntervalAverage_apply, map_smul]
  rw [← (operators τ).intervalIntegral_comp_comm
    ((hcontinuous seed).intervalIntegrable 0 L)]
  congr 1
  apply intervalIntegral.integral_congr
  intro s _hs
  change operators τ (operators s seed) = operators s (operators τ seed)
  rw [hcompose τ s, hcompose s τ, add_comm s τ]

/-- Transporting a strong interval average translates its integration window. -/
theorem strongOperatorIntervalAverage_along_representation_eq_shifted
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (operators : ℝ → E →L[ℝ] E) (L : ℝ) (hL : 0 < L)
    (hcontinuous : ∀ seed, Continuous (fun s => operators s seed))
    (hcontract : ∀ s, ‖operators s‖ ≤ 1)
    (hcompose : ∀ τ s seed,
      operators τ (operators s seed) = operators (s + τ) seed)
    (τ : ℝ) (seed : E) :
    operators τ
        (strongOperatorIntervalAverage operators L hL hcontinuous hcontract seed) =
      L⁻¹ • ∫ s in τ..L + τ, operators s seed := by
  rw [strongOperatorIntervalAverage_apply, map_smul]
  rw [← (operators τ).intervalIntegral_comp_comm
    ((hcontinuous seed).intervalIntegrable 0 L)]
  simp_rw [hcompose]
  rw [intervalIntegral.integral_comp_add_right
    (fun s => operators s seed) τ]
  simp only [zero_add]

/-- Every finite strong average belongs to the generator domain of its
one-parameter representation.  Its derivative is the endpoint difference
divided by the averaging length. -/
theorem strongOperatorIntervalAverage_hasDerivAt_along_representation
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    (operators : ℝ → E →L[ℝ] E) (L : ℝ) (hL : 0 < L)
    (hcontinuous : ∀ seed, Continuous (fun s => operators s seed))
    (hcontract : ∀ s, ‖operators s‖ ≤ 1)
    (hcompose : ∀ τ s seed,
      operators τ (operators s seed) = operators (s + τ) seed)
    (seed : E) :
    HasDerivAt
      (fun τ => operators τ
        (strongOperatorIntervalAverage operators L hL hcontinuous hcontract seed))
      (L⁻¹ • (operators L seed - operators 0 seed)) 0 := by
  let observable : ℝ → E := fun s => operators s seed
  have hobservable : Continuous observable := hcontinuous seed
  let primitive : ℝ → E := fun b => ∫ s in (0 : ℝ)..b, observable s
  have hprimitive : ∀ b : ℝ, HasDerivAt primitive (observable b) b := by
    intro b
    exact (hobservable.integral_hasStrictDerivAt 0 b).hasDerivAt
  have hupper : HasDerivAt (fun τ => primitive (L + τ))
      (observable (L + 0)) 0 :=
    (hprimitive (L + 0)).comp_const_add L 0
  have hlower : HasDerivAt primitive (observable 0) 0 := hprimitive 0
  have hfunction :
      (fun τ => operators τ
        (strongOperatorIntervalAverage operators L hL hcontinuous hcontract seed)) =
      fun τ => L⁻¹ • (primitive (L + τ) - primitive τ) := by
    funext τ
    rw [strongOperatorIntervalAverage_along_representation_eq_shifted
      operators L hL hcontinuous hcontract hcompose τ seed]
    dsimp [primitive]
    rw [intervalIntegral.integral_interval_sub_left
      (hobservable.intervalIntegrable 0 (L + τ))
      (hobservable.intervalIntegrable 0 τ)]
  rw [hfunction]
  change HasDerivAt
    (L⁻¹ • ((fun τ => primitive (L + τ)) - primitive))
    (L⁻¹ • (operators L seed - operators 0 seed)) 0
  simpa [observable] using (hupper.sub hlower).const_smul L⁻¹

/-! ## The actual average attached to a continuous measure-preserving flow -/

/-- The normalized Koopman average of a continuous measure-preserving flow,
constructed from strong `L²` continuity alone. -/
def measurePreservingFlowKoopmanAverage
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) : Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ :=
  strongOperatorIntervalAverage
    (measurePreservingFlowKoopman μ flow hmeasure) L hL
    (measurePreservingFlowKoopman_stronglyContinuous μ flow hmeasure)
    (measurePreservingFlowKoopman_norm_le_one μ flow hmeasure)

@[simp]
theorem measurePreservingFlowKoopmanAverage_apply
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (seed : Lp ℝ 2 μ) :
    measurePreservingFlowKoopmanAverage μ flow hmeasure L hL seed =
      L⁻¹ • ∫ s in (0 : ℝ)..L,
        measurePreservingFlowKoopman μ flow hmeasure s seed := by
  rfl

/-- The flow-induced average is a contraction on scalar `L²`. -/
theorem measurePreservingFlowKoopmanAverage_norm_le_one
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) :
    ‖measurePreservingFlowKoopmanAverage μ flow hmeasure L hL‖ ≤ 1 := by
  exact strongOperatorIntervalAverage_norm_le_one
    (measurePreservingFlowKoopman μ flow hmeasure) L hL
    (measurePreservingFlowKoopman_stronglyContinuous μ flow hmeasure)
    (measurePreservingFlowKoopman_norm_le_one μ flow hmeasure)

/-- The genuine flow average has the expected strong `L²` transport leakage
bound, proved from the endpoint intervals and the Koopman flow law. -/
theorem measurePreservingFlowKoopmanAverage_translate_sub_norm_le
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (τ : ℝ) (seed : Lp ℝ 2 μ) :
    ‖measurePreservingFlowKoopman μ flow hmeasure τ
        (measurePreservingFlowKoopmanAverage μ flow hmeasure L hL seed) -
      measurePreservingFlowKoopmanAverage μ flow hmeasure L hL seed‖ ≤
      (2 * |τ| / L) * ‖seed‖ := by
  exact strongOperatorIntervalAverage_translate_sub_norm_le
    (measurePreservingFlowKoopman μ flow hmeasure) L hL
    (measurePreservingFlowKoopman_stronglyContinuous μ flow hmeasure)
    (measurePreservingFlowKoopman_norm_le_one μ flow hmeasure)
    (measurePreservingFlowKoopman_compose μ flow hmeasure) τ seed

/-- Koopman transport commutes with the strong average constructed from the
same flow. -/
theorem measurePreservingFlowKoopmanAverage_commute
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (τ : ℝ) :
    measurePreservingFlowKoopman μ flow hmeasure τ ∘L
        measurePreservingFlowKoopmanAverage μ flow hmeasure L hL =
      measurePreservingFlowKoopmanAverage μ flow hmeasure L hL ∘L
        measurePreservingFlowKoopman μ flow hmeasure τ := by
  exact strongOperatorIntervalAverage_commute
    (measurePreservingFlowKoopman μ flow hmeasure) L hL
    (measurePreservingFlowKoopman_stronglyContinuous μ flow hmeasure)
    (measurePreservingFlowKoopman_norm_le_one μ flow hmeasure)
    (measurePreservingFlowKoopman_compose μ flow hmeasure) τ

/-- The strong Koopman average lies in the generator domain, with generator
given by the two endpoint transports. -/
theorem measurePreservingFlowKoopmanAverage_hasDerivAt
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (seed : Lp ℝ 2 μ) :
    HasDerivAt
      (fun τ => measurePreservingFlowKoopman μ flow hmeasure τ
        (measurePreservingFlowKoopmanAverage μ flow hmeasure L hL seed))
      (L⁻¹ •
        (measurePreservingFlowKoopman μ flow hmeasure L seed - seed)) 0 := by
  simpa only [measurePreservingFlowKoopmanAverage,
    measurePreservingFlowKoopman_zero_apply] using
    strongOperatorIntervalAverage_hasDerivAt_along_representation
      (measurePreservingFlowKoopman μ flow hmeasure) L hL
      (measurePreservingFlowKoopman_stronglyContinuous μ flow hmeasure)
      (measurePreservingFlowKoopman_norm_le_one μ flow hmeasure)
      (measurePreservingFlowKoopman_compose μ flow hmeasure) seed

/-! ## Flow-generated positive Fejér weights -/

/-- Apply the adjoint of the genuine strong Koopman average to its forward
average.  This is the flow-level Fejér weight used by the retained-amplitude
criterion. -/
def measurePreservingFlowFejerWeight
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (seed : Lp ℝ 2 μ) : Lp ℝ 2 μ :=
  adjointAveragedWeight
    (measurePreservingFlowKoopmanAverage μ flow hmeasure L hL) seed

/-- Backward-flow commutation of the forward average implies that the adjoint
average commutes with forward Koopman transport. -/
theorem measurePreservingFlowKoopmanAverage_adjoint_commute
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (τ : ℝ) :
    measurePreservingFlowKoopman μ flow hmeasure τ ∘L
        (measurePreservingFlowKoopmanAverage μ flow hmeasure L hL).adjoint =
      (measurePreservingFlowKoopmanAverage μ flow hmeasure L hL).adjoint ∘L
        measurePreservingFlowKoopman μ flow hmeasure τ := by
  have hback := measurePreservingFlowKoopmanAverage_commute
    μ flow hmeasure L hL (-τ)
  have hadjoint := congrArg ContinuousLinearMap.adjoint hback
  simpa only [ContinuousLinearMap.adjoint_comp,
    measurePreservingFlowKoopman_adjoint, neg_neg] using hadjoint.symm

/-- The signal of the flow-generated Fejér weight is exactly the squared
`L²` amplitude retained by the Koopman average. -/
theorem measurePreservingFlowFejerWeight_inner_seed_eq_norm_sq
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (seed : Lp ℝ 2 μ) :
    inner ℝ (measurePreservingFlowFejerWeight μ flow hmeasure L hL seed) seed =
      ‖measurePreservingFlowKoopmanAverage μ flow hmeasure L hL seed‖ ^ 2 := by
  exact adjointAveragedWeight_inner_seed_eq_norm_sq
    (measurePreservingFlowKoopmanAverage μ flow hmeasure L hL) seed

/-- The Fejér weight costs at most the retained forward-average amplitude in
`L²`; this is the normalization needed by the localized-helicity defect gap. -/
theorem measurePreservingFlowFejerWeight_norm_le_retained
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (seed : Lp ℝ 2 μ) :
    ‖measurePreservingFlowFejerWeight μ flow hmeasure L hL seed‖ ≤
      ‖measurePreservingFlowKoopmanAverage μ flow hmeasure L hL seed‖ := by
  exact adjointAveragedWeight_norm_le
    (measurePreservingFlowKoopmanAverage μ flow hmeasure L hL) seed
    (measurePreservingFlowKoopmanAverage_norm_le_one
      μ flow hmeasure L hL)

/-- Any nonzero component retained by the actual flow average gives a strictly
positive Fejér signal. -/
theorem measurePreservingFlowFejerWeight_inner_seed_pos
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (seed : Lp ℝ 2 μ)
    (hretained :
      measurePreservingFlowKoopmanAverage μ flow hmeasure L hL seed ≠ 0) :
    0 < inner ℝ
      (measurePreservingFlowFejerWeight μ flow hmeasure L hL seed) seed := by
  exact adjointAveragedWeight_inner_seed_pos
    (measurePreservingFlowKoopmanAverage μ flow hmeasure L hL) seed hretained

/-- The positive adjoint-averaged weight inherits the same explicit strong
transport leakage as the forward average.  Thus the Fejér sign repair does not
introduce an uncontrolled `δ_L`: its finite-time Koopman defect is at most
`2 |τ| ‖seed‖₂ / L`. -/
theorem measurePreservingFlowFejerWeight_translate_sub_norm_le
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (τ : ℝ) (seed : Lp ℝ 2 μ) :
    ‖measurePreservingFlowKoopman μ flow hmeasure τ
        (measurePreservingFlowFejerWeight μ flow hmeasure L hL seed) -
      measurePreservingFlowFejerWeight μ flow hmeasure L hL seed‖ ≤
      (2 * |τ| / L) * ‖seed‖ := by
  let A := measurePreservingFlowKoopmanAverage μ flow hmeasure L hL
  let U := measurePreservingFlowKoopman μ flow hmeasure τ
  have hcomm : U ∘L A.adjoint = A.adjoint ∘L U := by
    exact measurePreservingFlowKoopmanAverage_adjoint_commute
      μ flow hmeasure L hL τ
  have htransport : U (A.adjoint (A seed)) = A.adjoint (U (A seed)) := by
    change (U ∘L A.adjoint) (A seed) = (A.adjoint ∘L U) (A seed)
    rw [hcomm]
  have hAdjointNorm : ‖A.adjoint‖ ≤ 1 := by
    simpa [A] using
      measurePreservingFlowKoopmanAverage_norm_le_one
        μ flow hmeasure L hL
  change ‖U (A.adjoint (A seed)) - A.adjoint (A seed)‖ ≤ _
  rw [htransport, ← map_sub]
  calc
    ‖A.adjoint (U (A seed) - A seed)‖ ≤ ‖U (A seed) - A seed‖ := by
      simpa using A.adjoint.le_of_opNorm_le hAdjointNorm (U (A seed) - A seed)
    _ ≤ (2 * |τ| / L) * ‖seed‖ := by
      exact measurePreservingFlowKoopmanAverage_translate_sub_norm_le
        μ flow hmeasure L hL τ seed

/-- The flow-generated Fejér weight itself lies in the transport-generator
domain.  Its generator is the adjoint average applied to the forward endpoint
difference. -/
theorem measurePreservingFlowFejerWeight_hasDerivAt
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (seed : Lp ℝ 2 μ) :
    HasDerivAt
      (fun τ => measurePreservingFlowKoopman μ flow hmeasure τ
        (measurePreservingFlowFejerWeight μ flow hmeasure L hL seed))
      (L⁻¹ •
        (measurePreservingFlowKoopmanAverage μ flow hmeasure L hL).adjoint
          (measurePreservingFlowKoopman μ flow hmeasure L seed - seed)) 0 := by
  let A := measurePreservingFlowKoopmanAverage μ flow hmeasure L hL
  let endpoint := measurePreservingFlowKoopman μ flow hmeasure L seed - seed
  have hforward : HasDerivAt
      (fun τ => measurePreservingFlowKoopman μ flow hmeasure τ (A seed))
      (L⁻¹ • endpoint) 0 := by
    exact measurePreservingFlowKoopmanAverage_hasDerivAt
      μ flow hmeasure L hL seed
  have hadjoint : HasDerivAt
      (fun τ => A.adjoint
        (measurePreservingFlowKoopman μ flow hmeasure τ (A seed)))
      (A.adjoint (L⁻¹ • endpoint)) 0 :=
    A.adjoint.hasFDerivAt.comp_hasDerivAt 0 hforward
  have hfunction :
      (fun τ => measurePreservingFlowKoopman μ flow hmeasure τ
        (measurePreservingFlowFejerWeight μ flow hmeasure L hL seed)) =
      fun τ => A.adjoint
        (measurePreservingFlowKoopman μ flow hmeasure τ (A seed)) := by
    funext τ
    change
      (measurePreservingFlowKoopman μ flow hmeasure τ ∘L A.adjoint) (A seed) =
        (A.adjoint ∘L measurePreservingFlowKoopman μ flow hmeasure τ) (A seed)
    rw [measurePreservingFlowKoopmanAverage_adjoint_commute
      μ flow hmeasure L hL τ]
  rw [hfunction]
  simpa [A, endpoint] using hadjoint

/-- The generator leakage of the positive Fejér weight is no larger than
`2 ‖seed‖₂ / L`.  This is the infinitesimal `L²` version of the finite
transport-defect estimate and removes a formerly free leakage parameter. -/
theorem measurePreservingFlowFejerWeight_generator_norm_le
    {α : Type*} [MeasurableSpace α] [TopologicalSpace α]
    [BorelSpace α] [R1Space α]
    (μ : Measure α) [μ.InnerRegularCompactLTTop]
    [IsLocallyFiniteMeasure μ]
    (flow : Flow ℝ α)
    (hmeasure : ∀ s, MeasurePreserving (flow s) μ μ)
    (L : ℝ) (hL : 0 < L) (seed : Lp ℝ 2 μ) :
    ‖L⁻¹ •
        (measurePreservingFlowKoopmanAverage μ flow hmeasure L hL).adjoint
          (measurePreservingFlowKoopman μ flow hmeasure L seed - seed)‖ ≤
      (2 / L) * ‖seed‖ := by
  let A := measurePreservingFlowKoopmanAverage μ flow hmeasure L hL
  let U := measurePreservingFlowKoopman μ flow hmeasure L
  have hAdjointNorm : ‖A.adjoint‖ ≤ 1 := by
    simpa [A] using measurePreservingFlowKoopmanAverage_norm_le_one
      μ flow hmeasure L hL
  have hU : ‖U seed‖ ≤ ‖seed‖ := by
    simpa using U.le_of_opNorm_le
      (measurePreservingFlowKoopman_norm_le_one μ flow hmeasure L) seed
  have hendpoint : ‖U seed - seed‖ ≤ 2 * ‖seed‖ := by
    calc
      ‖U seed - seed‖ ≤ ‖U seed‖ + ‖seed‖ := norm_sub_le _ _
      _ ≤ ‖seed‖ + ‖seed‖ := add_le_add hU le_rfl
      _ = 2 * ‖seed‖ := by ring
  have hadjointStep : ‖A.adjoint (U seed - seed)‖ ≤ ‖U seed - seed‖ := by
    simpa using A.adjoint.le_of_opNorm_le hAdjointNorm (U seed - seed)
  have hadjoint : ‖A.adjoint (U seed - seed)‖ ≤ 2 * ‖seed‖ :=
    hadjointStep.trans hendpoint
  change ‖L⁻¹ • A.adjoint (U seed - seed)‖ ≤ _
  rw [norm_smul, Real.norm_eq_abs, abs_inv, abs_of_pos hL]
  calc
    L⁻¹ * ‖A.adjoint (U seed - seed)‖ ≤ L⁻¹ * (2 * ‖seed‖) :=
      mul_le_mul_of_nonneg_left hadjoint (inv_nonneg.mpr hL.le)
    _ = (2 / L) * ‖seed‖ := by field_simp

/-! ## Nonvacuity on the measured three-torus -/

/-- The identity flow preserves the actual Haar-volume measure on `Torus3`.
This gives a concrete inhabitant of every interface above. -/
theorem torus3_identityFlow_measurePreserving (s : ℝ) :
    MeasurePreserving (Flow.id ℝ Torus3 s)
      (volume : Measure Torus3) volume := by
  simpa using MeasurePreserving.id (volume : Measure Torus3)

/-- The concrete identity-flow Koopman operator acts as the identity on every
scalar `L²` seed. -/
theorem torus3_identityFlow_Koopman_apply
    (s : ℝ) (seed : Lp ℝ 2 (volume : Measure Torus3)) :
    measurePreservingFlowKoopman (volume : Measure Torus3)
      (Flow.id ℝ Torus3) torus3_identityFlow_measurePreserving s seed = seed := by
  change Lp.compMeasurePreserving id
    (torus3_identityFlow_measurePreserving s) seed = seed
  exact Lp.compMeasurePreserving_id_apply seed

/-- Averaging the concrete identity flow over any positive interval recovers
the seed exactly. -/
theorem torus3_identityFlow_KoopmanAverage_apply
    (L : ℝ) (hL : 0 < L) (seed : Lp ℝ 2 (volume : Measure Torus3)) :
    measurePreservingFlowKoopmanAverage (volume : Measure Torus3)
      (Flow.id ℝ Torus3) torus3_identityFlow_measurePreserving L hL seed = seed := by
  rw [measurePreservingFlowKoopmanAverage_apply]
  simp_rw [torus3_identityFlow_Koopman_apply]
  rw [intervalIntegral.integral_const]
  simp [hL.ne']

/-- Consequently the strongly continuous Koopman average is concretely
instantiated on the nonempty measured three-torus, with no bundled hypothetical
solution or operator-norm continuity premise. -/
theorem torus3_identityFlow_KoopmanAverage_norm_le_one
    (L : ℝ) (hL : 0 < L) :
    ‖measurePreservingFlowKoopmanAverage (volume : Measure Torus3)
        (Flow.id ℝ Torus3) torus3_identityFlow_measurePreserving L hL‖ ≤ 1 := by
  exact measurePreservingFlowKoopmanAverage_norm_le_one
    (volume : Measure Torus3) (Flow.id ℝ Torus3)
    torus3_identityFlow_measurePreserving L hL
