import NSFormal.Basic
import NSFormal.Anisotropy
import NSFormal.AnisotropicIntegration
import NSFormal.AnisotropicCriterion
import NSFormal.DirectorTensor
import NSFormal.Financing
import NSFormal.Lemma18
import NSFormal.QT1Moment
import NSFormal.Lemmas27
import NSFormal.CampaignAlgebra
import NSFormal.NewProofAlgebra
import NSFormal.Integrals
import NSFormal.Budget
import NSFormal.Vorticity
import NSFormal.VorticityMaximum
import NSFormal.VortexStretching
import NSFormal.Enstrophy
import NSFormal.DynamicCriterion
import NSFormal.DivCurl
import NSFormal.PeriodicSobolev
import NSFormal.PeriodicSobolevEuclidean
import NSFormal.PeriodicRegularity
import NSFormal.SpatialInterpolation
import NSFormal.KineticEnergy
import NSFormal.ConcreteDynamicCriterion
import NSFormal.LocalizedHelicity
import NSFormal.FlowAveraging
import NSFormal.FlowKoopman
import NSFormal.TorusFlow
import NSFormal.Domain
import NSFormal.MaxEnvelope
import NSFormal.PeriodicCalculus
import NSFormal.PeriodicIntegration
import NSFormal.Recurrence
import NSFormal.TorusVorticity
import NSFormal.NavierStokes
import NSFormal.VectorCalculus
import NSFormal.Stretching
import NSFormal.V002Repairs
import NSFormal.R15Closures
import NSFormal.FarField
import NSFormal.SpectralFlux
import NSFormal.LambFlux
